# Generated by Django 4.2.6 on 2023-12-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='Registro_Productos',
        ),
    ]
